# Generated by Django 4.0.4 on 2022-05-10 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('year', models.CharField(max_length=4)),
                ('rated', models.CharField(max_length=20)),
                ('released', models.CharField(max_length=50)),
                ('genre', models.TextField()),
                ('actors', models.TextField()),
                ('writer', models.TextField()),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('awards', models.TextField()),
                ('poster', models.CharField(max_length=200)),
                ('ratings', models.JSONField()),
                ('metascore', models.CharField(max_length=20)),
                ('imdb_rating', models.CharField(max_length=20)),
                ('imdb_votes', models.CharField(max_length=20)),
                ('imdb_id', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('movie', 'movie'), ('series', 'series'), ('episode', 'episode')], max_length=50)),
                ('total_seasons', models.IntegerField()),
                ('response', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movie')),
            ],
        ),
    ]
