# Generated by Django 4.0.4 on 2022-05-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_movie_actors_alter_movie_awards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
